FROM python:3.9-slim


ENV PYTHONUNBUFFERED True

Copy local code to the container image.
ENV APP_HOME /app
WORKDIR $APP_HOME
COPY . ./


RUN pip install Flask gunicorn

Run the web service on container startup. Here we use the gunicorn

CMD exec gunicorn --bind :$PORT --workers 1 --threads 8 --timeout 0 main:app